version: '3.0'

services:
  my-registry:
    image: registry:latest
    container_name: my-registry
    volumes:
      - registry:/var/lib/registry3
    ports:
      - "50000:5000"
    restart: unless-stopped
volumes:
  registry: